name: db_client
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  clock: ^1.1.2
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3: ^2.7.6

dev_dependencies:
  altive_lints: ^1.23.0
  build_runner: ^2.6.0
  custom_lint: ^0.8.0
  drift_dev: ^2.28.3
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
