name: db_client
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  clock: ^1.1.2
  drift: ^2.29.0
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  # Because drift_flutter depends on sqlite3 2.x.x
  # https://github.com/simolus3/drift/issues/3710
  sqlite3: ^2.9.4

dev_dependencies:
  altive_lints: ^1.25.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  drift_dev: ^2.29.0
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
