name: db_client
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  clock: ^1.1.2
  drift: ^2.28.0
  drift_flutter: ^0.2.5
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3: ^2.7.6

dev_dependencies:
  altive_lints: ^1.21.0
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  drift_dev: ^2.28.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
