name: provider_utils
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  package_info_plus: ^8.1.1
  riverpod_annotation: ^2.6.1
  simple_logger: ^1.10.0
  utils:
    path: ../utils

dev_dependencies:
  altive_lints: ^1.17.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  
