name: provider_utils
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  package_info_plus: ^8.3.0
  riverpod_annotation: ^3.0.0
  simple_logger: ^1.10.0
  utils:
    path: ../utils

dev_dependencies:
  altive_lints: ^1.23.0
  build_runner: ^2.6.0
  custom_lint: ^0.8.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0
