name: provider_utils
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  package_info_plus: ^9.0.0
  riverpod_annotation: ^3.0.3
  simple_logger: ^1.10.0
  utils:
    path: ../utils

dev_dependencies:
  altive_lints: ^1.25.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
