name: configurator
description: A Flutter package for Firebase Remote Config wrapper functionality.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  firebase_remote_config: ^6.1.2
  flutter:
    sdk: flutter
  # Because flutter depends on intl 1.16.0  .
  # https://github.com/flutter/flutter/blob/stable/packages/flutter/pubspec.yaml#L16
  meta: ^1.16.0

dev_dependencies:
  altive_lints: ^1.22.0
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  firebase_core: ^4.2.1
  firebase_core_platform_interface: ^6.0.2
  firebase_remote_config_platform_interface: ^2.0.5
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  plugin_platform_interface: ^2.1.8
