name: update_requester
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  configurator:
    path: ../../core/configurator/
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  version: ^3.0.2

dev_dependencies:
  altive_lints: ^1.22.0
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  mockito: ^5.4.6

flutter:
  uses-material-design: true
