name: update_requester
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  configurator:
    path: ../../core/configurator/
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  version: ^3.0.2

dev_dependencies:
  altive_lints: ^1.22.1
  build_runner: ^2.6.0
  custom_lint: ^0.8.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.11.1
  mockito: ^5.5.0

flutter:
  uses-material-design: true
