name: tracker
description: A Flutter package for Firebase Analytics wrapper functionality.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.32.6"

dependencies:
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5
  flutter:
    sdk: flutter
  meta: ^1.12.0

dev_dependencies:
  altive_lints: ^1.22.0
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  firebase_analytics_platform_interface: ^5.0.4
  firebase_core: ^4.2.1
  firebase_core_platform_interface: ^6.0.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
