name: in_app_reviewer
description: "In-app review prompting functionality for One Page diary app."
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  in_app_review: ^2.0.10
  prefs_client:
    path: ../../core/prefs_client

dev_dependencies:
  altive_lints: ^1.22.1
  build_runner: ^2.6.0
  custom_lint: ^0.8.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
