name: widgets
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  toastification: ^3.0.3
  utils:
    path: ../utils

dev_dependencies:
  altive_lints: ^1.23.0
  custom_lint: ^0.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
