name: widgets
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  toastification: ^3.0.3
  utils:
    path: ../utils

dev_dependencies:
  altive_lints: ^1.21.0
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
