name: exporter
description: "Export feature package"
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  clock: ^1.1.2
  db_client:
    path: ../../core/db_client/
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^12.0.1

dev_dependencies:
  altive_lints: ^1.25.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mockito: ^5.6.1
