name: utils
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  simple_logger: ^1.10.0

dev_dependencies:
  altive_lints: ^1.22.1
  custom_lint: ^0.8.0
  # Because flutter_test depends on fake_async 1.3.3.
  # https://github.com/flutter/flutter/blob/stable/packages/flutter_test/pubspec.yaml#L25
  fake_async: ^1.3.3
  flutter_test:
    sdk: flutter
