name: diary
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  clock: ^1.1.2
  db_client:
    path: ../../core/db_client/
  flutter:
    sdk: flutter
  utils:
    path: ../../core/utils/

dev_dependencies:
  altive_lints: ^1.23.0
  build_runner: ^2.6.0
  custom_lint: ^0.8.0
  mockito: ^5.5.0
  # Because flutter_test depends on test_api 0.7.4, test 1.25.x.
  # https://github.com/flutter/flutter/blob/stable/packages/flutter_test/pubspec.yaml#L15-L18
  test: ^1.26.2
