name: diary
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  clock: ^1.1.2
  db_client:
    path: ../../core/db_client/
  flutter:
    sdk: flutter
  utils:
    path: ../../core/utils/

dev_dependencies:
  altive_lints: ^1.21.0
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  mockito: ^5.4.6
  # Because flutter_test depends on test_api 0.7.4, test 1.25.x.
  # https://github.com/flutter/flutter/blob/stable/packages/flutter_test/pubspec.yaml#L15-L18
  test: ^1.25.15
