name: diary
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  clock: ^1.1.2
  db_client:
    path: ../../core/db_client/
  flutter:
    sdk: flutter
  utils:
    path: ../../core/utils/

dev_dependencies:
  altive_lints: ^1.25.0
  build_runner: ^2.10.3
  custom_lint: ^0.8.1
  mockito: ^5.5.1
  # Because flutter_test depends on test_api 0.7.7, test 1.26.x.
  # https://github.com/flutter/flutter/blob/stable/packages/flutter_test/pubspec.yaml#L15-L18
  test: ^1.26.3
