name: notification_client
description: A package for handling local notifications in the diary app.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  prefs_client:
    path: ../prefs_client
  timezone: ^0.10.1

dev_dependencies:
  altive_lints: ^1.25.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mockito: ^5.6.1
