name: haptics
description: A package that provides haptic feedback functionality with preference-based control.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  prefs_client:
    path: ../../core/prefs_client

dev_dependencies:
  altive_lints: ^1.25.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1
