name: scroll_calendar
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  gap: ^3.0.1
  # Because flutter depends on intl 0.20.2.
  # https://github.com/flutter/flutter/blob/stable/packages/flutter/pubspec.yaml#L42
  intl: ^0.20.2
  scrollable_positioned_list: ^0.3.8
  visibility_detector: ^0.4.0+2

dev_dependencies:
  altive_lints: ^1.21.0
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
